layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

topics:
  
projects: 
# The progects you want to display
  - MusicSignature
  - Mondrian
  - emergence-simulation
  - BackPacker
  - GameOfLife3D
  - FlappyCloud